PROJECT_ID = 'uploadnotes-2016'
PROJECT_URL = 'https://' + PROJECT_ID + '.appspot.com'
BUCKET_NAME = '/' + PROJECT_ID + 'appspot.com'
WEBSITE_URL = 'https://campusconnect-2016.herokuapp.com'
BUCKET_NAME = '/' + PROJECT_ID + '.appspot.com'
WEBSITE_URL = 'https://campusconnect-2016.herokuapp.com'
FCM_URL = 'https://fcm.googleapis.com/fcm/send'
FCM_AUTH_KEY = 'AIzaSyD4MtcG4R0LrZ42nskF1lpBQSYq0JT-a6Y'
