PROJECT_ID = 'uploadingtest-2016'
PROJECT_URL = 'https://' + PROJECT_ID + '.appspot.com'
BUCKET_NAME = '/' + PROJECT_ID + 'appspot.com'
WEBSITE_URL = 'https://campusconnect-2016.herokuapp.com'
BUCKET_NAME = '/' + PROJECT_ID + '.appspot.com'
WEBSITE_URL = 'https://campusconnect-2016.herokuapp.com'
